name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]

jobs:
    init:
        name: "Say Hello World"
        runs-on: ubuntu-latest
        steps:
            - name: "First step"
              run: |
                echo "Hello World"
                echo "Coucou la deuxième ligne" 