name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
# on: [push, workflow_dispatch]
on:
  push: ~
  workflow_dispatch: ~

jobs:
  init:
    name: "Initialize the project"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository" # Pour récupérer le code
        uses: actions/checkout@v4

      - name: "Setup node to last version"
        uses: "actions/setup-node@v4"
        with:
          node-version: latest

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: "Install Dependancies"
        run: |
          node -v
          npm ci
    
  build:
    needs: ["init"]
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: "Display files"
        run: ls
      - name: "Build the project"
        run: echo "Ton projet il est build"
  
  test:
    needs: ["build"]
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: "Make the tests"
        run: npm run test
        continue-on-error: true
    
  # notify:
  #   needs: ["test"]
  #   name: "Notify me"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Notify when It's finish"
  #       run: echo "CI OK"