name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]

jobs:
    init:
        name: "Say Hello World"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v4

            - name: "Setup node to last version"
              uses: "actions/setup-node@v4"
              with:
                node-version: latest

            - name: "Install Dependancies"
              run: |
                node -v
                npm ci

            - name: "Build"
              run: echo "Ton projet il est build"
            
            - name: "Test"
              run: npm run test
              continue-on-error: true

            - name: "Notify"
              run: echo "CI OK"